steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - ${GCLOUD_FUNCTION_NAME}
  - --region=${FUNCTION_REGION}
  - --source=.
  - --trigger-http
  - --allow-unauthenticated

  
